server:
  port: 8765

spring:
  application:
    name: api-gateway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

hystrix:
  command:
    default:
      execution:
      isolation:
      thread:
      timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

zuul:
  routes:
    user:
      # service-id é o spring.application.name do yml de cada api. Devem ser iguais.
      service-id: user
      path: /user/**
    worker:
      service-id: hr-worker
      path: /hr-worker/**
    payroll:
      service-id: hr-payroll
      path: /hr-payroll/**
    oauth:
      service-id: oauth
      path: /oauth/**
      # Habilita a comunicação usando headers para o login de app + user
      sensitive-headers: Cookie, Set-Cookie