# Porta aleatória
#server:
#  port: ${PORT:0}
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
#spring:
#  application:
#    name: hr-worker
#
#  datasource:
#    url: jdbc:h2:mem:testdbworker
#    username: sa
#    password:
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console/worker

